// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Luminy_Company_api.Context;

#nullable disable

namespace Luminy_Company_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240104181908_sqlserver")]
    partial class sqlserver
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Luminy_Company_api.Models.Compras", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Data_compra")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("PassagemId")
                    .HasColumnType("int");

                b.Property<double>("Total_compra")
                    .HasColumnType("float");

                b.Property<int>("ClienteId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PassagemId");

                b.HasIndex("ClienteId");

                b.ToTable("Compras");
            });

            modelBuilder.Entity("Luminy_Company_api.Models.Passagem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);


                b.Property<string>("Destino")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Preco")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.ToTable("Passagem");
            });

            modelBuilder.Entity("Luminy_Company_api.Models.Clientes", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nome")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Senha")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Clientes");
            });

            modelBuilder.Entity("Luminy_Company_api.Models.Compras", b =>
            {
                b.HasOne("Luminy_Company_api.Models.Livros", "Livro")
                    .WithMany("Compras")
                    .HasForeignKey("PassagemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Luminy_Company_api.Models.Clientes", "Cliente")
                    .WithMany("Compras")
                    .HasForeignKey("ClienteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Passagem");

                b.Navigation("Cliente");
            });

            modelBuilder.Entity("Luminy_Company_api.Models.Passagem", b =>
            {
                b.Navigation("Compras");
            });

            modelBuilder.Entity("Luminy_Company_api.Models.Clientes", b =>
            {
                b.Navigation("Compras");
            });
#pragma warning restore 612, 618
        }
    }
}